export default {
  USERNAME_ALREADY_TAKEN: 'USERNAME_ALREADY_TAKEN',
	INVALID_EMAIL: 'INVALID_EMAIL', 
	INVALID_PASSWORD: 'INVALID_PASSWORD',
	LOGIN_FAILED: 'LOGIN_FAILED',	
	USER_DOES_NOT_EXISTS: 'USER_DOES_NOT_EXISTS',
	IMAGE_MISSING: 'IMAGE_MISSING',
	RECIPIENTS_MISSING: 'RECIPIENTS_MISSING'
}
