
export const createUserActions = {
    CREATE_USER: 'CREATE_USER',
    CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',
    CREATE_USER_FAILURE: 'CREATE_USER_FAILURE',
  };

  export const loginUserActions = {
    LOGIN_USER: 'LOGIN_USER',
    LOGIN_USER_SUCCESS: 'LOGIN_USER_SUCCESS',
    LOGIN_USER_FAILURE: 'LOGIN_USER_FAILURE',
  }

  export const getAllUserDataActions = {
    GETTING_DATA: 'GETTING_DATA',
    SUMMARY_IS_FETCHED: 'SUMMARY_IS_FETCHED',
    GETTING_DATA_SUCCESS: 'GETTING_DATA_SUCCESS',
    GETTING_DATA_FAILURE:  'GETTING_DATA_FAILURE'  
  }