const errorCodes = {
	MISSING_PARAMETER: 'MISSING_PARAMETER',
	USER_DOES_NOT_EXISTS: 'USER_DOES_NOT_EXISTS',
	CONTACT_DOES_NOT_EXISTS: 'USER_DOES_NOT_EXISTS',
	ALREADY_A_CONTACT: 'ALREADY_A_CONTACT',
	IMAGE_COULD_NOT_BE_SAVED: 'IMAGE_COULD_NOT_BE_SAVED',
};

const errorStatuses = {
	USER_DOES_NOT_EXISTS: 400,
	CONTACT_DOES_NOT_EXISTS: 400,
	ALREADY_A_CONTACT: 400
};

module.exports = {
	errorCodes,
	errorStatuses
}

