const errorCodes = {
	MISSING_PARAMETER: 'MISSING_PARAMETER',
	USERNAME_ALREADY_TAKEN: 'USERNAME_ALREADY_TAKEN',
	INVALID_EMAIL: 'INVALID_EMAIL', 
	INVALID_PASSWORD: 'INVALID_PASSWORD',
	USER_DOES_NOT_EXISTS: 'USER_DOES_NOT_EXISTS',
	CONTACT_DOES_NOT_EXISTS: 'CONTACT_DOES_NOT_EXISTS',
	ALREADY_A_CONTACT: 'ALREADY_A_CONTACT',
	INVALID_IMAGE: 'INVALID_IMAGE',
	INVALID_RECIPIENT: 'INVALID_RECIPIENT',
	NOT_ALLOWED_TO_GET_MEMORY: 'NOT_ALLOWED_TO_GET_MEMORY',
	LOGIN_FAILED: 'LOGIN_FAILED',
	INVALID_CLIENT_ID: 'INVALID_CLIENT_ID',
	UNAUTHORIZED: 'UNAUTHORIZED',
	NOT_A_CONTACT: 'NOT_A_CONTACT'
};

const errorStatuses = {
	CONTACT_DOES_NOT_EXISTS: 404,
	ALREADY_A_CONTACT: 400,
	INVALID_IMAGE: 400,
	NOT_ALLOWED_TO_GET_MEMORY: 403,
	USER_DOES_NOT_EXISTS: 404,
	MISSING_PARAMETER: 400,
	USERNAME_ALREADY_TAKEN: 403,
	LOGIN_FAILED: 403,
	UNAUTHORIZED: 403,
	INVALID_EMAIL: 400,
	INVALID_PASSWORD: 400,
	INVALID_CLIENT_ID: 400,
	NOT_A_CONTACT: 400,
};

module.exports = {
	errorCodes,
	errorStatuses
}

