const errorCodes = {
	MISSING_PARAMETER: 'MISSING_PARAMETER',
	USER_DOES_NOT_EXISTS: 'USER_DOES_NOT_EXISTS',
	CONTACT_DOES_NOT_EXISTS: 'USER_DOES_NOT_EXISTS',
	ALREADY_A_CONTACT: 'ALREADY_A_CONTACT',
	INVALID_IMAGE: 'INVALID_IMAGE',
	INVALID_RECIPIENT: 'INVALID_RECIPIENT',
	NOT_ALLOWED_TO_GET_MEMORY: 'NOT_ALLOWED_TO_GET_MEMORY',
};

const errorStatuses = {
	CONTACT_DOES_NOT_EXISTS: 404,
	ALREADY_A_CONTACT: 400,
	INVALID_IMAGE: 400,
	NOT_ALLOWED_TO_GET_MEMORY: 403,
	USER_DOES_NOT_EXISTS: 404,
};

module.exports = {
	errorCodes,
	errorStatuses
}

